// src/routes/resume/+page.svelte
<div class="overflow-y-hidden">
  <a href="/Morgan_Dean_Resume_Jul_2026.pdf">(download)</a>
  <object
    title="Resume: Jun 2026"
    type="application/pdf"
    class="h-11/12 w-full pr-2"
    data="/Morgan_Dean_Resume_Jul_2026.pdf"
  >
    <p>Your browser doesn't support PDF viewers. Please download above.</p>
  </object>
</div>

// src/views/Resume.vue
<template>
    <div class="overflow-y-hidden">
        <a href="/Morgan_Dean_Resume_Mar_2023">(download)</a>
        <object type="application/pdf" class="w-full h-11/12 pr-2" data="/Morgan_Dean_Resume_Mar_2023.pdf">
            <p>Your browser doesn't support PDF viewers. Please download above.</p>
        </object>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'Resume'
});
</script>

<style scoped>

</style>
