// src/lib/components/ToolTip.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { fade } from 'svelte/transition';

  interface Props {
    text: string;
    left?: string;
    arrowLeft?: string;
    children: Snippet;
  }

  let { text, left = '0%', arrowLeft = '50%', children }: Props = $props();

  let visible = $state(false);
</script>

<span
  role="tooltip"
  class="relative inline-block"
  onmouseenter={() => (visible = true)}
  onmouseleave={() => (visible = false)}
  onfocusin={() => (visible = true)}
  onfocusout={() => (visible = false)}
>
  {@render children()}

  {#if visible}
    <span
      role="tooltip"
      transition:fade={{ duration: 100 }}
      style="left: {left}"
      class="pointer-events-none absolute bottom-full z-50 mb-2 w-max rounded-md bg-gray-800 px-2 py-1 text-xs whitespace-nowrap text-white transition duration-150 dark:bg-gray-200 dark:text-gray-800"
    >
      {text}
      <span
        style="left: {arrowLeft}"
        class="absolute top-full -ml-1 border-4 border-transparent border-t-gray-800 dark:border-t-gray-200"
      ></span>
    </span>
  {/if}
</span>

// src/components/ToolTip.vue
<template>
    <div class="tooltip">
        <slot/>
        <div class="tooltip-text" :style="{left}">
            {{ text }}
            <span class="tooltip-arrow" :style="{left: arrowLeft}"></span>
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue';

export default defineComponent({
    name: 'ToolTip',
    props: {
        text: {
            type: String,
            default: ''
        },
        left: {
            type: String,
            default: '50%'
        },
        arrowLeft: {
            type: String,
            default: '50%'
        }
    }
});
</script>

<style lang="scss" scoped>
.tooltip {
    position: relative;
    user-select: none;
    display: inline-block;
}

.tooltip .tooltip-text {
    transition: all .3s;
    white-space: nowrap;
    opacity: 0;
    z-index: -1;
    background-color: black;
    color: #fff;
    text-align: center;
    border-radius: 6px;
    padding: 5px 8px;
    position: absolute;
    bottom: 150%;
    margin-left: -60px;
}

.tooltip .tooltip-arrow {
    content: "";
    position: absolute;
    top: 100%;
    left: 50%;
    margin-left: -5px;
    border-width: 5px;
    border-style: solid;
    border-color: black transparent transparent transparent;
}

.tooltip:hover .tooltip-text {
    opacity: .85;
    z-index: 1;
}
</style>
